<a href="https://colab.research.google.com/github/AB-uui/pythonEX/blob/main/Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Exercise

In [2]:
import numpy as np

### Ex 1:  
Import data from file located at  "./data/inflammation-01.csv"

In [5]:
# fname = "./data/inflammation-01.csv"
#your code here

import requests

# URL of the CSV file
url = "https://swcarpentry.github.io/python-novice-inflammation/data/inflammation-01.csv"
file_name = "inflammation-01.csv"

# Download the file
try:
    response = requests.get(url)
    response.raise_for_status()  # Raise an error for bad status codes
    with open(file_name, "wb") as file:
        file.write(response.content)
    print(f"File downloaded successfully as {file_name}")
except requests.exceptions.RequestException as e:
    print(f"Error downloading the file: {e}")
    exit()

# Load the file with numpy
try:
    data = np.loadtxt(fname=file_name, delimiter=",")
    print("Data loaded successfully!")
    print(data)
except Exception as e:
    print(f"Error reading the file with numpy: {e}")


File downloaded successfully as inflammation-01.csv
Data loaded successfully!
[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


### Ex 2:
1. Print the last value of the array, that is, the value at the last row and last column.
1. Print the entire last row.
1. Print the entire last column.

In [6]:
#your code here
print(data[-1,-1])
print(data[-1])
print(data[:,-1])

0.0
[ 0.  0.  1.  0.  3.  2.  5.  4.  8.  2.  9.  3.  3. 10. 12.  9. 14. 11.
 13.  8.  6. 18. 11.  9. 13. 11.  8.  5.  5.  2.  8.  5.  3.  5.  4.  1.
  3.  1.  1.  0.]
[0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]


### Ex 3:
Calculate the square root of the data using numpy. Print the result for the first 5 columns of the first 3 rows.

In [8]:
#your code here
data_sqrt = np.sqrt(data)
print(data_sqrt[:3,:5])

[[0.         0.         1.         1.73205081 1.        ]
 [0.         1.         1.41421356 1.         1.41421356]
 [0.         1.         1.         1.73205081 1.73205081]]


### Ex 4:
On which day did each patient had the most inflammation?

In [16]:
#your code here

data_argmax = data.argmax(axis=1)
print(data_argmax)

[19 20 20 20 19 18 21 20 18 20 19 22 17 19 17 18 21 21 17 21 21 22 18 19
 20 19 22 23 20 18 19 20 15 25 19 23 18 18 20 18 20 20 21 19 21 18 20 15
 24 18 19 20 21 19 18 17 23 19 22 21]


### Ex 5:
Create an array with the inverse ($1/x$) of the even numbers lower than or equal to 100.

In [29]:
#your code here

# even_numbers = np.arange(2, 101, 2)
# %timeit np.reciprocal(even_numbers.astype(float))  #the good
# %timeit even_numbers.astype(float)**-1
# %timeit 1 / even_numbers

inverses_even_numbers = np.reciprocal(np.arange(2, 101, 2).astype(float))
print(inverses_even_numbers)


[0.5        0.25       0.16666667 0.125      0.1        0.08333333
 0.07142857 0.0625     0.05555556 0.05       0.04545455 0.04166667
 0.03846154 0.03571429 0.03333333 0.03125    0.02941176 0.02777778
 0.02631579 0.025      0.02380952 0.02272727 0.02173913 0.02083333
 0.02       0.01923077 0.01851852 0.01785714 0.01724138 0.01666667
 0.01612903 0.015625   0.01515152 0.01470588 0.01428571 0.01388889
 0.01351351 0.01315789 0.01282051 0.0125     0.01219512 0.01190476
 0.01162791 0.01136364 0.01111111 0.01086957 0.0106383  0.01041667
 0.01020408 0.01      ]


### Ex 6:
Skim through the documentation for `np.ravel`, and use this function to construct the array:
```py
[1 0 0 0 1 0 0 0 1]
```

In [39]:
#you can use the function help in order to see the documentation
help(np.ravel)

In [38]:
#your code here

mat_eye_flat = np.ravel(np.eye(3).astype(int))
print(mat_eye_flat)

[1 0 0 0 1 0 0 0 1]


### Ex 7: Broadcasting
Given a 1D array X, calculate the differences between each two elements of X using broadcasting and save it to array D.

In [42]:
X = np.linspace(0, 1, 50)

In [61]:
# your code here

# D = abs(X[:, None] - X)
D = abs(X.reshape(50,1) - X)
print(D.reshape(50,50))

[[0.         0.02040816 0.04081633 ... 0.95918367 0.97959184 1.        ]
 [0.02040816 0.         0.02040816 ... 0.93877551 0.95918367 0.97959184]
 [0.04081633 0.02040816 0.         ... 0.91836735 0.93877551 0.95918367]
 ...
 [0.95918367 0.93877551 0.91836735 ... 0.         0.02040816 0.04081633]
 [0.97959184 0.95918367 0.93877551 ... 0.02040816 0.         0.02040816]
 [1.         0.97959184 0.95918367 ... 0.04081633 0.02040816 0.        ]]


In [62]:
assert D.shape == (50, 50)
assert (D.diagonal() == 0).all()
assert (D[5,5] == D[-5,-5])

### Ex 8:
![image.png](attachment:image.png)

Given a 1D array, negate (i.e. turn to negative) all elements which are between 3 and 8 (including both), in place (i.e. without creating a new array).

In [63]:
Z = np.arange(11)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [68]:
# Your code here
# Z[(Z >= 3) & (Z <= 8)] *= -1
# print(Z)
Z[:] = np.where((Z >= 3) & (Z <= 8), -Z, Z)
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])